name: QAA-slack-poster
on: [pull_request, repository_dispatch]

env: 
  node-version: 12.x

jobs: 
  post-to-slack:
    runs-on: ubuntu-latest
    outputs: 
      tags: ${{steps.testing.outputs.text}}
    steps: 
      - name: Dump Github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: Testing variable
        id: testing 
        run: |
          AUDIT=$(node ./src/test.js)
          echo "::set-output name=text::$AUDIT"
      - name: Run script 
        uses: ./
        with: 
          webhook: ${{ secrets.TEST_WEBHOOK }}
          run_status: "passed"
          bluescape_url: "stg1.bluescape.com"
          testrail_project_id: "15"
          extra_text:  ${{ steps.testing.outputs.text }}
