name: QAA-slack-poster
on: [pull_request]

env: 
  node-version: 12.x
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

jobs: 
  post-to-slack:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run script 
        uses: ./
        with: 
          webhook: "${{ env.SLACK_WEBHOOK_URL }}"
          gh_run_id: "some_run_id"
          run_status: "passed"
          bluescape_url: "abc"
          testrail_project_id: "15"
          repo_token: ${{ secrets.GITHUB_TOKEN }}